export const AUTH_type = {
  USER_REGISTER: "USER_REGISTER",
  USER_LOGIN: "USER_LOGIN",
};
export const TODO_TYPE = {
  TODO_CREATE: "TODO_CREATE",
  TODO_DELETE: "TODO_DELETE",
  TODO_LIST: "TODO_LIST",
  TODO_UPDATE: "TODO_UPDATE",
};
